---
title: Boundless
timezone: America/Phoenix
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@boundless.com
description: Boundless
repository: abasalilov/boundless-site
plugins:
  - jekyll-feed
  - jekyll-sitemap
header_pages:
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
markdown: kramdown
permalink: pretty
sass:
  load_paths:
    - _sass
    - node_modules
