---
title: Boundless
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@boundless.com
description: Boundless
repository: abasalilov/boundless-site
plugins:
- jekyll-feed
- jekyll-sitemap
header_pages: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- update_boostrap.sh
